device: cuda:0
epochs: 100
model:
  args:
    num_classes: 85
  load_ckpt:
    fc_out: 81
    path: ./experiments/46_2023-07-16 11:15:27_best_baseline2/Video2Roll_bestf1.pth
  type: Video2RollNet
optimizer:
  args:
    lr: 0.001
  type: Adam
test_dataset:
- args:
    img_root: ./data/rousseau/images_align
    label_root: ./data/rousseau/labels_align
    max_key: 83
    min_key: 3
  augmentation: null
  loader_args:
    batch_size: 64
    num_workers: 16
  type: Video2RollDataset
- args:
    img_root: ./data/kassia/images
    label_root: ./data/kassia/labels
    max_key: 83
    min_key: 3
  augmentation: null
  loader_args:
    batch_size: 64
    num_workers: 16
  type: Video2RollDataset
- args:
    img_root: ./data/ytdataset/images_nopad
    label_root: ./data/ytdataset/labels_audeo
    max_key: 83
    min_key: 3
  augmentation: null
  loader_args:
    batch_size: 64
    num_workers: 16
  type: Video2RollDataset
train_dataset:
  args:
    img_root: ./data/train_customrousseau/images
    label_root: ./data/train_customrousseau/labels
    max_key: 83
    min_key: 3
  augmentation: null
  loader_args:
    batch_size: 64
    num_workers: 16
  type: Video2RollDataset
wandb:
  run_name: customdata_with_rousseau
  use: true
