train_dataset:
    type: "Video2RollDataset"
    args:
        img_root: "./data/train_all_nopad/images"
        label_root: "./data/train_all_nopad/labels"
        min_key: 0
        max_key: 84
    loader_args:
        batch_size: 64
        num_workers: 16
test_dataset:
    - type: "Video2RollDataset"
      args:
        img_root: "./data/ytdataset/images_nopad"
        label_root: "./data/ytdataset/labels_audeo"
        min_key: 0
        max_key: 84
      loader_args:
        batch_size: 64
        num_workers: 16
    - type: "Video2RollDataset"
      args:
        img_root: "./data/bommelpiano/images"
        label_root: "./data/bommelpiano/labels"
        min_key: 0
        max_key: 84
      loader_args:
        batch_size: 64
        num_workers: 16
    - type: "Video2RollDataset"
      args:
        img_root: "./data/MIDItest/images"
        label_root: "./data/MIDItest/labels"
        min_key: 0
        max_key: 84
      loader_args:
        batch_size: 64
        num_workers: 16
model:
    type: "Video2RollNet"
    args:
        num_classes: 51
    load_ckpt: 
        path: "./Audeo/Audeo_github/Video2Roll_models/Video2RollNet.pth"
        fc_out: 85 # checkpoint에서 사용한 num_classes를 지정. 모델의 num_classes와 동일하면 null 사용.
optimizer:
    type: "Adam"
    args:
        lr: 0.001
device: "cuda:0"
epochs: 100
wandb:
    use: True
    run_name: "nopadding"